version: '2'

services:
  postgis:
    ports:
      # - "6543:5432"
      - "6543:5432"

  qgis-server:
    environment:
      - DEBUG=True
      - QGIS_LOG_FILE=/tmp/qgis-server/qgis.log
      - QGIS_SERVER_LOG_FILE=/tmp/qgis-server/qgis-server.log
      # Log level 0 is the lowest (catch all), 5 is the highest (only fatal error)
      - QGIS_DEBUG=0
      - QGIS_SERVER_LOG_LEVEL=0
    ports:
      # - "9003:80"
      - "9003:80"

  django:
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '../src/geonode:/usr/src/app'
      - './pycharm_helpers/django:/root/.pycharm_helpers'
    environment:
      - DEBUG=True
      - SITEURL=http://192.168.1.121/
      - GEONODE_BASE_URL=http://192.168.1.121/
      - QGIS_SERVER_URL=http://qgis-server/
      - GEOSERVER_BASE_URL=http://geoserver:8080/geoserver/
    command: /usr/sbin/sshd -D
    ports:
      # - "9000:22"
      - "9000:22"

  nginx:
    ports:
      # - "80:80"
      - "80:80"

  celery:
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '../src/geonode:/usr/src/app'
      - './pycharm_helpers/celery:/root/.pycharm_helpers'
    environment:
      - DEBUG=True
    command: /usr/sbin/sshd -D
    ports:
      # - "9001:22"
      - "9001:22"

  inasafe-headless:
    environment:
      - INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR=/home/output/
      - INASAFE_HEADLESS_DEPLOY_OUTPUT_URL=http://inasafe-output/output/
      - QGIS_LOG_FILE=/tmp/inasafe/realtime/logs/qgis.log
      - QGIS_DEBUG_FILE=/tmp/inasafe/realtime/logs/qgis-debug.log
      - QGIS_DEBUG=0
      - INASAFE_WORK_DIR=/tmp/inasafe
    volumes:
      - './pycharm_helpers/inasafe-headless:/root/.pycharm_helpers'
    command: /start-celery.sh dev
    ports:
      # - "9002:22"
      - "9002:22"

  inasafe-headless-analysis:
    environment:
      - INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR=/home/output/
      - INASAFE_HEADLESS_DEPLOY_OUTPUT_URL=http://inasafe-output/output/
      - QGIS_LOG_FILE=/tmp/inasafe/realtime/logs/qgis.log
      - QGIS_DEBUG_FILE=/tmp/inasafe/realtime/logs/qgis-debug.log
      - QGIS_DEBUG=0
      - INASAFE_WORK_DIR=/tmp/inasafe
    volumes:
      - './pycharm_helpers/inasafe-headless-analysis:/root/.pycharm_helpers'
    command: /start-celery.sh dev
    ports:
      # - "9002:22"
      - "9004:22"
